### ISSUE TITLE
How to download new mongodump binary to update to 4.0.4?

### ISSUE THREAD

**Issue by AJB99** [llangit/lambda-mongocluster-s3#1]
Hi there, great work. This is a handy function.

The problem I'm running into is that I need to upgrade the version of `mongodump` that gets loaded when the Lambda function executes, but I can't figure out where to download it.

How did you get the 3.6.4 version in the first place?

Thanks in advance for any help!

**Comment by llangit** [comment]
Hi!
I've downloaded it from the MongoDB website. Go to https://www.mongodb.com/download-center/community, then select "Server", then "Community Server", then version 4.0.5 and OS "macOS 64-bit x64". In the downloaded archive, the binary can be found in the "bin" folder.

**Comment by llangit** [comment]
No wait, you have to download the Amazon Linux version: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon-4.0.5.tgz
